export const IpcChannels = {
  gameStateUpdate: 'gameState:update',
  gameStateScreenChange: 'gameState:screenChange',
  mcpHealth: 'mcp:health',
  recommendationReady: 'recommendation:ready',
  /** Pull the current state/health/recommendation when an overlay (re)loads. */
  overlaySnapshot: 'overlay:snapshot',
  overlaySetInteractive: 'overlay:setInteractive',
  overlayTogglePinned: 'overlay:togglePinned',
  overlayPinnedChanged: 'overlay:pinnedChanged',
  overlayOpenModInstall: 'overlay:openModInstall',
  modInstallBundled: 'mod:installBundled',
  settingsGet: 'settings:get',
  settingsSet: 'settings:set',
  settingsChanged: 'settings:changed',
  annotationsUpdate: 'annotations:update',
  overlaySetCompact: 'overlay:setCompact',
  calibrationStart: 'calibration:start',
  calibrationCancel: 'calibration:cancel',
  calibrationClick: 'calibration:click',
  calibrationState: 'calibration:state',
  overlayQuit: 'overlay:quit',
  // --- Hub window + browse / tier lists ---
  hubOpen: 'hub:open',
  openExternal: 'app:openExternal',
  clipboardWrite: 'clipboard:write',
  gameStatus: 'game:status',
  hubMinimize: 'hub:minimize',
  hubMaximizeToggle: 'hub:maximizeToggle',
  hubClose: 'hub:close',
  tierDataGet: 'tierData:get',
  compendiumGet: 'compendium:get',
  tierListsList: 'tierList:list',
  tierListSave: 'tierList:save',
  tierListDelete: 'tierList:delete',
  tierListExport: 'tierList:export',
  tierListImport: 'tierList:import',
  tierListSetActive: 'tierList:setActive',
  tierListActiveChanged: 'tierList:activeChanged'
} as const

export type IpcChannel = (typeof IpcChannels)[keyof typeof IpcChannels]
